<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>bcaa2192-05f6-4a5a-a140-38597fa38a5d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="readme.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="azure.identity" Version="1.21.0" />
    <PackageReference Include="azure.resourcemanager" Version="1.14.0" />
    <PackageReference Include="azure.resourcemanager.sql" Version="1.4.0" />
    <PackageReference Include="dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
    <PackageReference Include="microsoft.data.sqlclient" Version="6.1.4" />
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="Sentry.Azure.Functions.Worker" Version="5.16.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>