name: Build, Test, and Deploy to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Azure.HyperScale.ElasticPool.AutoScaler'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) CHECK OUT CODE
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) SET UP .NET
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3) RESTORE DEPENDENCIES
      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      # 4) BUILD
      - name: Build project
        run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --no-restore

      # 5) TEST
      - name: Run Tests
        run: dotnet test Azure.HyperScale.ElasticPool.AutoScaler.Tests --configuration Release

      # 6) PUBLISH THE APP ONCE
      - name: Publish Function App
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./publish

      # 9) DEPLOY TO PRODUCTION
      - name: Deploy to PRODUCTION
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          slot-name: PRODUCTION
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ./publish